# Generated by Django 5.2.4 on 2025-07-22 12:59

import theatre.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=theatre.models.create_custom_path),
        ),
    ]
